void rainbow(CRGB *, int );
void rainbowWithGlitter(CRGB *_leds, int num_leds);
void rainbow_scaling();
void fire();
void fireSparks();
void fireRainbow();
void noise1();
void noise2();
void noise3();
void blendwave();
void confetti();
void ripple_blur();
void sinelon();
void dot_beat();
void juggle();
void wave2(CRGB*, int);
void pride(CRGB*, int);
void duplicate_led();
void show_grow( CRGB *_leds, int num_leds, bool up , unsigned char hue, unsigned char bright, int _delay_msec);